CREATE TABLE CHARA( 
    CHA_NO NUMBER PRIMARY KEY,
    CHA_NAME VARCHAR2(30),
    CHA_AGE NUMBER,
    CHA_WEA VARCHAR2(50),
    JOB VARCHAR2(10),
    STATUS VARCHAR2(10) DEFAULT '평온'
);

CREATE TABLE WEA(
    WEA_NO NUMBER PRIMARY KEY,
    WEA_NAME VARCHAR2(50),
    WEA_DE NUMBER
);




-- WEA에 WEA_NAME을 참조한다.
ALTER TABLE CHARA ADD FOREIGN KEY (CHA_WEA) REFERENCES WEA_NAME;

-- wea data
INSERT INTO WEA VALUES (01, '미정의1', '10');
INSERT INTO WEA VALUES (02, '이쑤시개', '5');
INSERT INTO WEA VALUES (03, '미정의3', '20');
INSERT INTO WEA VALUES (04, '미정의4', '30');
INSERT INTO WEA VALUES (05, '미정의5', '100');
INSERT INTO WEA VALUES (06, '미정의6', '22');
INSERT INTO WEA VALUES (07, '미정의7', '55');
INSERT INTO WEA VALUES (08, '미정의8', '33');
INSERT INTO WEA VALUES (09, '먼지덩어리', '1');
INSERT INTO WEA VALUES (10, '솜', '0');




DELETE FROM WEA
WHERE WEA_NO = '10';

DROP TABLE CHARA;
DROP TABLE WEA;